# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rpc

# /// \brief: headers that are stored in an int
# /// so they need to be inclusive. That is, you can turn on
# /// many flags at the same time, i.e.: enable checksum and
# /// have the payload be zlib compressed.
# ///
class compression_flags(object):
# /// \brief compression not set
    none = 0
# /// \brief useful for preventing outgoing filters from
# /// enabling some compression
    disabled = 1
# /// \brief zstd compression
    zstd = 2
# /// \brief lz4 compression
    lz4 = 3

